services:
  web:
    build:
      context: .
    command: flask run --host=0.0.0.0 --debug
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ./schema.sql:/app/schema.sql
      - huggingface_cache:/root/.cache/huggingface
    ports:
      - "5001:5000"
    env_file:
      - .env
    networks:
      - app_net
    depends_on:
      - db
      - tei-embedding
      # - tei-reranker

  db:
    image: pgvector/pgvector:pg17-trixie
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_net

  tei-embedding:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7.4
    command:
      - --model-id
      - nomic-ai/nomic-embed-text-v1.5
      - --max-batch-tokens
      - "128"
      - --max-client-batch-size
      - "4"
      - --auto-truncate 
    ports:
      - "8080:80"
    volumes:
      - huggingface_cache:/data
    networks:
      - app_net
      - tei_net

  # tei-reranker:
  #   image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7.4
  #   command:
  #     - --model-id
  #     - cross-encoder/ms-marco-MiniLM-L2-v2
  #     - --max-batch-tokens
  #     - "2048"
  #     - --max-client-batch-size
  #     - "8"
  #     - --auto-truncate
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - huggingface_cache:/data
  #   networks:
  #     - app_net
  #     - tei_net

volumes:
  postgres_data:
  huggingface_cache:

networks:
  app_net:
  tei_net:
    name: tei_net